FROM node:latest

ARG proxy

RUN mkdir -p /app/node_modules && chown -R node:node /app
WORKDIR /app
COPY compliance-by-design-demo/package*.json ./
USER node
RUN npm install
COPY --chown=node:node compliance-by-design-demo/ ./

RUN npm config set proxy ${proxy}

EXPOSE 3000 3001
CMD [ "npm", "start" ]
