version: "3.7"
services:
  redis-kvk-cache:
    image: redis:5.0.8
    container_name: redis-kvk-cache
    ports:
      - 6379:6379

  react-dev-server:
    build:
      context: compliance-by-design-demo
      dockerfile: Dockerfile.dev
    env_file:
      - dev.env
    ports:
      - 3000:3000
    stdin_open: true

  api-server:
    depends_on:
      - redis-kvk-cache
    build:
      context: kvk-api
      dockerfile: Dockerfile.dev
    env_file:
      - dev.env
    ports:
      - 3001:3001
    stdin_open: true

