version: "3.7"
services:
  redis-kvk-cache:
    image: redis:5.0.8
    container_name: redis-kvk-cache
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]

  redis-rate-limit:
    image: redis:5.0.8
    container_name: redis-rate-limit
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]

  react-dev-server:
    build:
      context: compliance-by-design-demo
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    ports:
      - 3000:3000
    stdin_open: true

  api-server:
    depends_on:
      - redis-kvk-cache
      - redis-rate-limit
    build:
      context: kvk-api
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    ports:
      - 3001:3001
    stdin_open: true

