FROM node:latest

RUN mkdir -p /app/node_modules && chown -R node:node /app
WORKDIR /app
COPY package*.json ./
USER node
RUN npm install
COPY --chown=node:node . ./

EXPOSE 3001
CMD [ "node", "app.js" ]
